---
project_name: gsd
env:
  - CGO_ENABLED=0
builds:
  - ldflags:
    - "-X {{.Env.VERSION_PKG}}.Branch={{.Env.BRANCH}}"
    - "-X {{.Env.VERSION_PKG}}.BuildDate={{.Env.DATE}}"
    - "-X {{.Env.VERSION_PKG}}.GitSHA1={{.Env.COMMIT}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  skip: false