---
language: go
matrix:
  include:
    - go: 1.13.x

before_install:
  - go get golang.org/x/lint/golint

install:
  - # skip

script:
  - gofmt -d .
  - golint $(go list ./...)
  - go vet $(go list ./...)
  - go build
