---
branches:
  only:
  - master
sudo: required
language: go
matrix:
  include:
    - go: 1.13.5
env:
  matrix:
  - GO_RELEASER_VERSION=v0.123.3

before_install:
  - GO111MODULE=off go get -u golang.org/x/lint/golint

before_script:
  - curl -L -o /tmp/goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/${GO_RELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz
  - sudo tar -xzf /tmp/goreleaser.tar.gz -C /usr/local/bin/ && sudo chmod +x /usr/local/bin/goreleaser

install:
  - # skip

script:
  - make test-dirty
  - make test-release
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
